### ISSUE TITLE
salt furnace crashes when connected with a fluid pipe added by other mod

### ISSUE THREAD

**Issue by rioil** [Tsuteto/TofuCraft-MC1.7.10#7]
## Current Behavior

Salt furnace crashes when connected with a fluid pipe added by other mod.

example. (connect with mechanical pipe added by Mekanism)
![2022-02-27_12 10 22](https://user-images.githubusercontent.com/19888023/155866585-471be5f2-5a93-4d67-8d00-94e4779e5d21.png)

## Steps to Reproduce

1. Connect a salt furnace with a fluid pipe added by other mod
2. Restart Minecraft
3. Minecraft crashes when loading the world because of NullPointerException

## Context (Environment)

- Minecraft 1.7.10
- Forge 10.13.4.1614
- TofuCraft-2.1.7-mc1.7.10.jar

**Comment by Tsuteto** [comment]
Thank you for your report with a detailed description!
I'll accept your RP later.
